// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema21 extends i0.VersionedSchema {
  Schema21({required super.database}) : super(version: 21);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    kanjis,
    kanas,
    vocabularyEntries,
    kanjiTranslations,
    vocabularyTranslations,
    sentences,
    sentenceTranslations,
    exercises,
    grammarLessons,
    grammarExercises,
    grammarLessonProgress,
    grammarLessonStarts,
    grammarChapterUnlocks,
    progressEntries,
    srsCards,
  ];
  late final Shape0 kanjis = Shape0(
    source: i0.VersionedTable(
      entityName: 'kanjis',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 kanas = Shape1(
    source: i0.VersionedTable(
      entityName: 'kanas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 vocabularyEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'vocabulary_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_2,
        _column_5,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 kanjiTranslations = Shape3(
    source: i0.VersionedTable(
      entityName: 'kanji_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kanji_id, locale)'],
      columns: [_column_16, _column_17, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 vocabularyTranslations = Shape4(
    source: i0.VersionedTable(
      entityName: 'vocabulary_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(vocabulary_id, locale)'],
      columns: [_column_18, _column_17, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 sentences = Shape5(
    source: i0.VersionedTable(
      entityName: 'sentences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_19,
        _column_20,
        _column_18,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sentenceTranslations = Shape6(
    source: i0.VersionedTable(
      entityName: 'sentence_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sentence_id, locale)'],
      columns: [_column_24, _column_17, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 exercises = Shape7(
    source: i0.VersionedTable(
      entityName: 'exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_17,
        _column_8,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 grammarLessons = Shape8(
    source: i0.VersionedTable(
      entityName: 'grammar_lessons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 grammarExercises = Shape9(
    source: i0.VersionedTable(
      entityName: 'grammar_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_41, _column_39, _column_8, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 grammarLessonProgress = Shape10(
    source: i0.VersionedTable(
      entityName: 'grammar_lesson_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(lesson_path)'],
      columns: [_column_41, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 grammarLessonStarts = Shape11(
    source: i0.VersionedTable(
      entityName: 'grammar_lesson_starts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(lesson_path)'],
      columns: [_column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 grammarChapterUnlocks = Shape12(
    source: i0.VersionedTable(
      entityName: 'grammar_chapter_unlocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_key)'],
      columns: [_column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 progressEntries = Shape13(
    source: i0.VersionedTable(
      entityName: 'progress_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(item_type, item_id)'],
      columns: [_column_0, _column_45, _column_46, _column_47, _column_48],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 srsCards = Shape14(
    source: i0.VersionedTable(
      entityName: 'srs_cards',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(item_type, item_id)'],
      columns: [_column_45, _column_46, _column_49, _column_50, _column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get character =>
      columnsByName['character']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meaning =>
      columnsByName['meaning']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get onReading =>
      columnsByName['on_reading']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kunReading =>
      columnsByName['kun_reading']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jlptLevel =>
      columnsByName['jlpt_level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get svg =>
      columnsByName['svg']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'character',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meaning',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'on_reading',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kun_reading',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'jlpt_level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'svg',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get character =>
      columnsByName['character']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get romaji =>
      columnsByName['romaji']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get row =>
      columnsByName['row']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kanaGroup =>
      columnsByName['kana_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get slot =>
      columnsByName['slot']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'romaji',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'row',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kana_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'slot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get word =>
      columnsByName['word']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reading =>
      columnsByName['reading']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meaning =>
      columnsByName['meaning']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jlptLevel =>
      columnsByName['jlpt_level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get partOfSpeech =>
      columnsByName['part_of_speech']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get kanjiId =>
      columnsByName['kanji_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'word',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reading',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'part_of_speech',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'kanji_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'REFERENCES kanjis(id)',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get kanjiId =>
      columnsByName['kanji_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meaning =>
      columnsByName['meaning']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'kanji_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES kanjis(id)',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locale',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get vocabularyId =>
      columnsByName['vocabulary_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meaning =>
      columnsByName['meaning']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'vocabulary_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES vocabulary_entries(id)',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get japanese =>
      columnsByName['japanese']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get targetWord =>
      columnsByName['target_word']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get vocabularyId =>
      columnsByName['vocabulary_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get furiganaBefore =>
      columnsByName['furigana_before']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get furiganaAfter =>
      columnsByName['furigana_after']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get furigana =>
      columnsByName['furigana']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'japanese',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_word',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'furigana_before',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'furigana_after',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'furigana',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get sentenceId =>
      columnsByName['sentence_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get translation =>
      columnsByName['translation']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sentence_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES sentences(id)',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'translation',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get prompt =>
      columnsByName['prompt']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get answer =>
      columnsByName['answer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get distractors =>
      columnsByName['distractors']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'prompt',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'answer',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'distractors',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locale =>
      columnsByName['locale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get level =>
      columnsByName['level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get themeName =>
      columnsByName['theme_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get themeDescription =>
      columnsByName['theme_description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get chapter =>
      columnsByName['chapter']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get blocksJson =>
      columnsByName['blocks_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orderIndex =>
      columnsByName['order_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get difficulty =>
      columnsByName['difficulty']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locale',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'en\'',
      defaultValue: const i1.CustomExpression('\'en\''),
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'theme_description',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chapter',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'blocks_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'difficulty',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lessonPath =>
      columnsByName['lesson_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get orderIndex =>
      columnsByName['order_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dataJson =>
      columnsByName['data_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'lesson_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'data_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get lessonPath =>
      columnsByName['lesson_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get readAt =>
      columnsByName['read_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'read_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get lessonPath =>
      columnsByName['lesson_path']! as i1.GeneratedColumn<String>;
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get chapterKey =>
      columnsByName['chapter_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chapter_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get itemType =>
      columnsByName['item_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get itemId =>
      columnsByName['item_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isKnown =>
      columnsByName['is_known']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get toggledAt =>
      columnsByName['toggled_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'item_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_known',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_known IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'toggled_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get itemType =>
      columnsByName['item_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get itemId =>
      columnsByName['item_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get due =>
      columnsByName['due']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get firstSeenAt =>
      columnsByName['first_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cardJson =>
      columnsByName['card_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'due',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'first_seen_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'card_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema22 extends i0.VersionedSchema {
  Schema22({required super.database}) : super(version: 22);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    kanjis,
    kanas,
    vocabularyEntries,
    kanjiTranslations,
    vocabularyTranslations,
    sentences,
    sentenceTranslations,
    exercises,
    grammarLessons,
    grammarExercises,
    grammarLessonProgress,
    grammarLessonStarts,
    grammarChapterUnlocks,
    progressEntries,
    srsCards,
  ];
  late final Shape0 kanjis = Shape0(
    source: i0.VersionedTable(
      entityName: 'kanjis',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 kanas = Shape1(
    source: i0.VersionedTable(
      entityName: 'kanas',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 vocabularyEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'vocabulary_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_12,
        _column_13,
        _column_2,
        _column_5,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 kanjiTranslations = Shape3(
    source: i0.VersionedTable(
      entityName: 'kanji_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(kanji_id, locale)'],
      columns: [_column_16, _column_17, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 vocabularyTranslations = Shape4(
    source: i0.VersionedTable(
      entityName: 'vocabulary_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(vocabulary_id, locale)'],
      columns: [_column_18, _column_17, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 sentences = Shape5(
    source: i0.VersionedTable(
      entityName: 'sentences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_19,
        _column_20,
        _column_18,
        _column_21,
        _column_22,
        _column_23,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sentenceTranslations = Shape6(
    source: i0.VersionedTable(
      entityName: 'sentence_translations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(sentence_id, locale)'],
      columns: [_column_24, _column_17, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 exercises = Shape7(
    source: i0.VersionedTable(
      entityName: 'exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_17,
        _column_8,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 grammarLessons = Shape8(
    source: i0.VersionedTable(
      entityName: 'grammar_lessons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 grammarExercises = Shape9(
    source: i0.VersionedTable(
      entityName: 'grammar_exercises',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_41, _column_39, _column_8, _column_42],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 grammarLessonProgress = Shape10(
    source: i0.VersionedTable(
      entityName: 'grammar_lesson_progress',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(lesson_path)'],
      columns: [_column_41, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 grammarLessonStarts = Shape11(
    source: i0.VersionedTable(
      entityName: 'grammar_lesson_starts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(lesson_path)'],
      columns: [_column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 grammarChapterUnlocks = Shape12(
    source: i0.VersionedTable(
      entityName: 'grammar_chapter_unlocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(chapter_key)'],
      columns: [_column_44],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 progressEntries = Shape13(
    source: i0.VersionedTable(
      entityName: 'progress_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(item_type, item_id)'],
      columns: [_column_0, _column_45, _column_46, _column_47, _column_48],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 srsCards = Shape14(
    source: i0.VersionedTable(
      entityName: 'srs_cards',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(item_type, item_id)'],
      columns: [_column_45, _column_46, _column_49, _column_50, _column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema21 schema) from20To21,
  required Future<void> Function(i1.Migrator m, Schema22 schema) from21To22,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 20:
        final schema = Schema21(database: database);
        final migrator = i1.Migrator(database, schema);
        await from20To21(migrator, schema);
        return 21;
      case 21:
        final schema = Schema22(database: database);
        final migrator = i1.Migrator(database, schema);
        await from21To22(migrator, schema);
        return 22;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema21 schema) from20To21,
  required Future<void> Function(i1.Migrator m, Schema22 schema) from21To22,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from20To21: from20To21, from21To22: from21To22),
);
